# Generated by Django 2.2.3 on 2019-07-07 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MSA', '0003_auto_20190707_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='address',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='birthday',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='company',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='describe',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='job',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='phone',
            field=models.CharField(default=None, max_length=32),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='school',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='sex',
            field=models.CharField(default=None, max_length=32),
        ),
    ]
