# Generated by Django 2.2.3 on 2019-07-07 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MSA', '0004_auto_20190707_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='address',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='birthday',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='company',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='describe',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='job',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='phone',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='school',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='sex',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
    ]
