# Generated by Django 2.2.3 on 2019-07-08 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MSA', '0006_userinfo_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analyse',
            fields=[
                ('id', models.IntegerField(max_length=11, primary_key=True, serialize=False)),
                ('type', models.DateField(max_length=32)),
                ('path', models.CharField(max_length=32)),
                ('descrip', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upid', models.IntegerField(max_length=11)),
                ('time', models.DateField()),
                ('content', models.CharField(max_length=255)),
                ('mid', models.IntegerField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.IntegerField(max_length=11, primary_key=True, serialize=False)),
                ('indid', models.IntegerField(max_length=11)),
                ('description', models.CharField(max_length=255)),
                ('emotion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Focus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(max_length=11)),
                ('indid', models.IntegerField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='IndustryInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inname', models.CharField(max_length=32)),
                ('description', models.CharField(default=None, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=32)),
                ('startime', models.DateField()),
                ('deadline', models.DateField()),
                ('done', models.IntegerField(default=0)),
                ('mid', models.IntegerField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(max_length=11)),
                ('title', models.CharField(max_length=32)),
                ('A', models.CharField(default=None, max_length=32, null=True)),
                ('B', models.CharField(default=None, max_length=32, null=True)),
                ('C', models.CharField(default=None, max_length=32, null=True)),
                ('D', models.CharField(default=None, max_length=32, null=True)),
                ('E', models.CharField(default=None, max_length=32, null=True)),
                ('F', models.CharField(default=None, max_length=32, null=True)),
                ('pid', models.IntegerField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Questionfill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(max_length=11)),
                ('time', models.TimeField()),
                ('qid', models.IntegerField(max_length=11)),
            ],
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='address',
            field=models.TextField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='describe',
            field=models.TextField(default=None, max_length=200, null=True),
        ),
    ]
