# Generated by Django 2.2.3 on 2019-07-10 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MSA', '0007_auto_20190708_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.IntegerField(default=1, max_length=11),
        ),
    ]
