# Generated by Django 2.2.3 on 2019-07-12 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MSA', '0010_auto_20190712_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyse',
            name='nega',
            field=models.IntegerField(default='0'),
        ),
    ]
