# Generated by Django 2.2.3 on 2019-07-12 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MSA', '0011_auto_20190712_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyse',
            name='conser',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='d10',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='d12',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='d15',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='d3',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='d7',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='nega',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='posi',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='sunega',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='suposi',
            field=models.IntegerField(default=0),
        ),
    ]
