# Generated by Django 2.2.3 on 2019-07-12 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MSA', '0012_auto_20190712_1118'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Analyse',
        ),
    ]
