# Generated by Django 2.2.3 on 2019-07-12 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MSA', '0013_delete_analyse'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IndustryInfo',
        ),
    ]
