# Generated by Django 2.2.3 on 2019-07-12 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MSA', '0014_delete_industryinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Focus',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
