# Generated by Django 2.2.3 on 2019-07-12 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MSA', '0015_auto_20190712_1128'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Board',
        ),
        migrations.DeleteModel(
            name='Paper',
        ),
        migrations.DeleteModel(
            name='Questionfill',
        ),
    ]
