# Generated by Django 2.2.3 on 2019-07-12 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MSA', '0017_delete_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
